<?php

namespace Database\Seeders;

use App\Enums\RealEstateType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Ramsey\Uuid\Uuid;

class ResidentialComplexRealEstateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $names = [
            'Abay Residence',
            '4YOU',
            '4Hills',
            '12 месяцев',
            'Abay 130',
            'Adem Village',
            'Adal Residence',
            'AFD Plaza',
            'Agat',
            'Ak Bulak Chalet',
            'AL’FARABI 27',
            'Alatau Golf Residences',
            'Alatau Green Village',
            'Alatau City',
            'Alatau Hills',
            'Alatau Village',
            'Alash Residence',
            'Alim',
            'Ala Park',
            'Alma City',
            'ALMA VILLA',
            'Alma Village',
            'КГ Alma Arasan Luxury Villas',
            'Amir',
            'Jardin',
            'Apple Park',
            'Apple Town',
            'Arbat',
            'Arlan',
            'Arnau',
            'Art Residence',
            'Art Villa',
            'Artville Алма-Арасан (КГ)',
            'Ashyq Tobe',
            'Assem Plaza',
            'Atameken Tower',
            'Atameken',
            'Athletic village',
            'Atlant',
            'Atria',
            'Auezov City',
            'Aul resort Chalet Village',
            'Aulet',
            'BAIKONYR',
            'Baganashil Residence',
            'Bayterek Residence',
            'BASS Townhouse',
            'BarnVille',
            'Basenova10',
            'Beilgravia Villas Almaty',
            'Belbulaq Hills Townhouse',
            'Bella Villa (КГ)',
            'Belle View',
            'Besagash',
            'Beverly Hills',
            'Bloom House',
            'BlackBerry Hills',
            'Braun',
            'Bright Hills',
            'CALIFORNIA',
            'Capital Club',
            'Castle Rock',
            'Chocolate',
            'Central Avenue',
            'Central Esentai Residence',
            'Central Park Residence',
            'City Park',
            'City Plus',
            'City Villa',
            'Cordial',
            'Crystal Air Village (КГ)',
            'Damac House',
            'Dial Residence',
            'Diamond Hills',
            'Dolce Vita Residence',
            'Dostar',
            'Dostyk',
            'Dostyk Residence',
            'Double Star',
            'Dragon City',
            'Elif Garden',
            'Ermensai Club',
            'Estet',
            'Europe city',
            'Evim Novo',
            'Family Club',
            'Four Seasons',
            'Four Seasons Villa',
            'Galileo Terrace',
            'Gagarin Park',
            'Gagarin Terrace',
            'Garden Villa',
            'Gulder',
            'Gorky Park Residence',
            'Gorny Residence',
            'Gorny Hills',
            'Grand Town',
            'Grande vie',
            'Green Landia',
            'Green',
            'Gul Ana',
            'Eco Green',
            'Eco Park',
            'Eco Park 2',
            'Element',
            'Elif Towers',
            'Elite Life',
            'Esentai Apartments',
            'Esentai River Townhouse',
            'Esentai Palace',
            'Esentai City',
            'Exclusive Life',
            'Exclusive Star',
            'Exclusive Time',
            'Exclusive Юбилейный',
            'Exclusive Residence',
            'Falconcity',
            'Family comfort',
            'Famous Town',
            'Favorit',
            'Felicita',
            'Forum Plus',
            'Forum Residence',
            'Harmony 2',
            'Hayat Park',
            'Hayat Apartments',
            'Heaven',
            'Hill Town Almaty',
            'Hill Town Residence',
            'Home Village',
            'Hyde Park',
            'Ideal Residence',
            'ile de France',
            'IRIS HOME',
            'Izumrud Residence',
            'Jasmine',
            'Jasmine Garden',
            'Jazz-квартал',
            'Jer-Ana Residence',
            'Jetisu Park',
            'Jubilee Hills',
            'Kayra',
            'Kaplan House',
            'Kerey Residence',
            'Koktobe city',
            'Lafayette',
            'Lamiya',
            'Lancashire',
            'LakeTown',
            'Latifa residence',
            'La Verde',
            'Levitas',
            'Lifetown',
            'Lotos Terrace',
            'Lumiere',
            'Luxury Park',
            'Luxushaus',
            'Miras Garden Village',
            'Miras Sweet Home',
            'Medeu City',
            'Mega Tower Almaty',
            'Megapolis',
            'MEKEN',
            'Melide',
            'Merey Terrace',
            'METROPOLE',
            'Miras Park',
            'Monolux Residence',
            'Mountain Park',
            'Mountain Drive',
            'Mountain Resort',
            'Moskva',
            'Nef Uptown',
            'Nest grand',
            'Nomad',
            'Nomad 2',
            'Nomad City',
            'Novella',
            'Navoi 3.0',
            'NS – Tau',
            'Nur-Ay Residence',
            'Nurly Dala',
            'ONER',
            'O-JET',
            'Olymp Residence',
            'Orchard Residences',
            'Orion',
            'Orion II',
            'Ortau',
            'Oscar',
            'Opera',
            'Parmigiano Country Club',
            'Parmigiano Family Resort',
            'Parmigiano Club House',
            'Palm Valley',
            'Palladium',
            'PARASAT',
            'Park House',
            'Pine Hill',
            'Pioneer',
            'Presidents Park',
            'Primavera',
            'Qadam',
            'Qarasai Park',
            'Rams luxury',
            'Rams city',
            'R-House',
            'RAIYMBEK',
            'Remizovka',
            'Remizovka Town',
            'Rich',
            'Riviera',
            'River Hills',
            'River House',
            'River Park',
            'River Time',
            'Riverside',
            'Royal',
            'Royal Gardens',
            'Samal Prestige',
            'Samal Tower',
            'Sandel',
            'Syattilik',
            'SAXON YARD',
            'Sensata City',
            'Serenity Park',
            'Seven Hills',
            'Silverwood',
            'Silver Hills',
            'SIRIUS',
            'Shahar City',
            'SOFIA',
            'Solar Homes',
            'Soho 17',
            'Sorrento',
            'Suly’ Tan',
            'Sun City',
            'Sun Garden',
            'Sun Villa',
            'Sun Hills',
            'Sholpan City',
            'Sweet Home Garden',
            'SOVMIN',
            'Tamarix',
            'Tau-house',
            'Tau Sani',
            'Terra',
            'Terracotta',
            'Terrenkur Terrace',
            'Varlamova',
            'Vostochka.kz',
            'Vivat Promenade',
            'Union',
            'Ush Qońyr',
            'UTEGEN',
            'White Fort',
            'Woodland Village',
            'Y-Fit House',
            'ZARYA',
            'ZHARKYN',
            'Zodiac',
            'Абай',
            'Адиет',
            'Admiral',
            'Азия',
            'Айгерим',
            'Айнабулак',
            'Айна',
            'Айсулу',
            'Ак Бота',
            'Акбулак',
            'Ак Булак Life',
            'Академия-1',
            'Академия-2',
            'Академия на Жамбыла 26',
            'Акварель',
            'Ак жол - Отау',
            'Акжар Тау',
            'Ак Алем',
            'Ак-Кайын',
            'Аккент',
            'Акмарал',
            'Акниет',
            'Аксай 5',
            'Алатау',
            'Алатау Ажары',
            'Алатау (КГ)',
            'Алатау Плюс (КГ)',
            'Алгабас (КГ)',
            'Алем (КГ)',
            'Алем (Әлем)',
            'Алма',
            'Алма-Ата',
            'Алмалы',
            'Алмалы-1',
            'Алматы Тауэрс',
            'Алтын Ауыл',
            'Алтын Булак 1',
            'Алтын Булак 2',
            'Алтын Есик',
            'Алтын Заман',
            'Алтын Орда',
            'Алтын Сити',
            'Алтынсарин',
            'Алматы Пана',
            'Алма Тау',
            'Альпийские Луга (КГ)',
            'Аль-Фараби',
            'Альтаир',
            'Аманат',
            'Амани (КГ)',
            'Амаль',
            'Арай',
            'Ария',
            'Арман',
            'Арман Вилла',
            'Арман Жолдар',
            'Арыстан',
            'Асем Тау (КГ)',
            'Аскар Тау',
            'Аскарбек',
            'Аспан Сити',
            'Астана',
            'Асыл Тау',
            'Асыл Тобе',
            'Асыл Уя',
            'Ата',
            'Атакент',
            'Атлас',
            'Атмосфера',
            'Аэлита',
            'Баганашил Севен Старс',
            'Базис на Достык',
            'Базис на Зенкова 33',
            'Базис на Чайковского',
            'Байсал',
            'Бай–тал',
            'Байтерек (КГ)',
            'Бакытты омир',
            'Баракат',
            'Бастау',
            'Батыр',
            'Бейбарыс Билдинг',
            'Бельбулак (КГ)',
            'Береке',
            'Берекет',
            'Бес Тулга',
            'Ботанический Бульвар',
            'Ботанический Cад',
            'Бродвей',
            'ЖК по Бузурбаева, 4',
            'Бухар Жырау Тауэрс',
            'ЖК в мкр. Саялы',
            'Вавилон',
            'ВЕК на Байганина',
            'ВЕК на Навои',
            'Венский дом',
            'Верный',
            'Версаль',
            'Весна',
            'Весновка',
            'Виктория',
            'Восточный Парк',
            'Восход',
            'Гармония',
            'Гаухартас',
            'Горная Долина',
            'Горное Солнце',
            'Горстрой на Аль-Фараби - Маркова',
            'Горстрой на ул. Кажымухана, дом 4',
            'Горстрой Самал 3, дом 21',
            'Гранд Алатау',
            'Даймонд Групп',
            'Два Богатыря на Сатпаева - Байсеитова 49, 42',
            'Депутатский',
            'Джетысуская 4',
            'Диалин',
            'Династия',
            'Долина роз',
            'Дом на Абая',
            'Дом на Гагарина',
            'Дом на Утеген батыра',
            'Достык',
            'Достык, дом 290',
            'Думан',
            'Дуэт',
            'Европейский квартал',
            'Европолис',
            'Евразия',
            'Многофункциональный жилой комплекс Евразия',
            'Есентай',
            'Жагалау - 46 квартал',
            'Жайлы',
            'Жайляу',
            'Жайсан',
            'Жана Гасыр',
            'Жана Жетысу',
            'Жана Куат (КГ)',
            'Жандосова',
            'ЖанЕл (КГ)',
            'Жасмин',
            'Жастар Mag',
            'Жастар-2 Mag',
            'Жастар Атамекен',
            'Женева',
            'Жеруйык',
            'Жетысу',
            'ЖК на Ташкентской',
            'Звезда Востока',
            'Зеленая Долина',
            'Зеленые Холмы (КГ)',
            'Изумрудный город',
            'Импорио',
            'Иннова Резидентс',
            'Каргалы',
            'Карлыгаш',
            'Каусар',
            'КГ Карасу',
            'КГ Тау Дала',
            'КД Алатау',
            'КД EVIM',
            'Керемет',
            'Клубный дом DeVille',
            'Клубный дом - W',
            'Кокжиек',
            'Кок Жер',
            'Кокше',
            'Комильфо',
            'Комфорт Плюс',
            'Космо',
            'Комфорт',
            'Комфорт Сити',
            'Котельникова',
            'Куаныш',
            'КУАТ на Достык - Сатпаева',
            'КУАТ на Барибаева - Гоголя',
            'КУАТ на Ескараева',
            'КУАТ на Маркова-Попова',
            'КУАТ на Масанчи - Абая',
            'КУАТ на Панфилова - Гоголя',
            'КУАТ на Сатпаева - Гагарина',
            'КУАТ на Торайгырова - Саина',
            'КУАТ на Фурманова - Казыбек-би',
            'Кулан',
            'Кунбел',
            'Лайлек',
            'Ласточкино гнездо',
            'LEGENDA',
            'Лотос',
            'Люксембург',
            'Люксембургский Сад (ЖК Оскар)',
            'Максат',
            'Максима на Райымбека',
            'Максима Резидентс',
            'Мамыр',
            'Манхеттан (29 квартал)',
            'МБ 52',
            'Мега Сайран',
            'Медеу Парк',
            'Меркур Град',
            'Меркур Град, 25',
            'Меркур Град, 27',
            'Меркур Тауэрс',
            'Мечта на Минина',
            'Мечта на Казыбек би',
            'МЖК по ул. Исаева, 125',
            'Мирный',
            'Мкр Жетысу-3',
            'Мкр Жулдыз',
            'Мкр Кулагер',
            'Мкр Таугуль',
            'Молодежный',
            'Молодежный на Тулебаева',
            'Мюнхен',
            'На Бокеева',
            'На Богенбай Батыра',
            'На Дунаевского',
            'На Ладыгина',
            'На Тулебаева',
            'На Тимирязева — Желтоксан',
            'Науаи',
            'Нахимова, 16',
            'Наурыз',
            'Наурыз-2',
            'НИКО Джамбула - Чайковского',
            'НИКО на Раимбека - Момышулы',
            'НИКО на Сатпаева - Луганского',
            'НИКО на Сатпаева - Чайковского',
            'НИКО на Сейфуллина - Физкультурной',
            'НИКО на Токтабаева - Навои',
            'НИКО на Толе би - Абдулиных',
            'НИКО на Толе би - Момышулы',
            'НИКО-2 на Толе би - Абдулиных',
            'Новый мир (КГ)',
            'Новый Мир на Радостовца - Утепова',
            'Новый Мир-2 на Радостовца - Утепова',
            'Новый Центр',
            'Ностальжи',
            'Нур Тобе',
            'Нурия',
            'Нұрлы дала',
            'Нуркент',
            'Нурлы Тау',
            'Овация',
            'Олд Базис',
            'Олимп',
            'Оркендеу',
            'Отау',
            'Оркен',
            'Отрар',
            'Панорама',
            'Парк Горького',
            'Парк Резиденс',
            'Персия',
            'Пионер',
            'Престиж Алатау',
            'Персия',
            'По Абая - Мамышулы',
            'По Аль-Фараби - Розыбакиева',
            'По Достоевского',
            'По Жамбыла',
            'По Кабанбай-Батыра',
            'По Луганского',
            'По Макатаева',
            'По Молдагалиева - Акынова',
            'По Навои - Рыскулбекова',
            'По Нурмакова',
            'По Пушкина - Тургенская',
            'По Спасской',
            'По Тимирязева',
            'По Шагабудинова',
            'Посольский',
            'Премьера',
            'Престиж',
            'Прогресс',
            'Радужный берег',
            'Рамс Абая - Манаса',
            'Рамс мкр Казахстан',
            'Рамс мкр Коктем по Тимирязева-Шашкина',
            'Рамс Бухар - Жырау - Ауэзова',
            'Рамс Муратбаева - Кабанбай батыра',
            'Рапсодия',
            'Раушан',
            'Реал Алматы',
            'Резиденция',
            'Ремизовка',
            'Ренессанс',
            'Ресми Групп',
            'Родник',
            'Родник-1',
            'Сайран',
            'Сакура',
            'Салем',
            'Салем-2',
            'Самал Делюкс',
            'Самга',
            'Сантаун (КГ)',
            'Сарыарка',
            'Сатти',
            'Северный',
            'Северное кольцо',
            'Сезам',
            'Сенім',
            'Симфония',
            'Современный',
            'Солнечная Долина',
            'Солнечная Долина (КГ)',
            'Солнечный Квартал',
            'Социал',
            'Спутник',
            'Столичный Центр',
            'Сункар',
            'Талисман',
            'Тан Нуры',
            'Тараз',
            'Тау Каргалы',
            'Тау Коктем',
            'Тау Самал (КГ)',
            'Тау Самал на Мендыкулова',
            'Тау Самал на Навои',
            'Тау Терек',
            'Тау Шатыр',
            'Таунхаус',
            'Таунхаусы Мирас',
            'Таун Хаус',
            'Театральный',
            'Тенгиз Тауэрс',
            'Теремки',
            'Терренкур',
            'Толе би Тау',
            'Томирис',
            'Три Богатыря',
            'Триумф 1',
            'Триумф 2',
            'Тюркуаз Тауэрс',
            'Улытау',
            'Уш-Сункар',
            'Уш-Тобе',
            'Фантазия',
            'Хан-Тенгри',
            'Хуторок',
            'Центральный',
            'Центральный На Тулебаева Кирова',
            'Цюрих',
            'Цитадель',
            'Чешские террасы',
            'ШАПАГАТ',
            'Шанырак',
            'Шахар',
            'Шахристан',
            'Швейцария',
            'Шолпан',
            'Шугыла',
            'Ырысты',
            'Шугыла-Сити',
            'Эдельвейс',
            'Эдельвейс (КГ)',
            'Эйвон',
            'Элит-1 на Зенкова',
            'Элит-2 на Калдаякова',
            'Эталон (Ремизовка)',
            'Эталон (На Райымбека)',
            'Этюд',
            'Южный Дуэт',
        ];

        foreach ($names as $name) {
            $residentialComplexId = Uuid::fromString(strtolower(Str::orderedUuid()))->getBytes();

            DB::table('real_estates')->insert([
                'id' => $residentialComplexId,
                'type_id' => RealEstateType::residentialComplex,
                'address' => 'ЖК адрес пока не указан',
                'city_id' => 1
            ]);

            DB::table('real_estate_attributes')->insert([
                'key' => 'name',
                'value' => $name,
                'real_estate_id' => $residentialComplexId
            ]);
        }
    }
}
